### ISSUE TITLE
Bug in processor atmospheric correction - Processor not supported

### ISSUE THREAD

**Issue by raphaelrpl** [brazil-data-cube/bdc-collection-builder#208]
The following errors occurs while start atm-correction task:

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/app/bdc_collection_builder/celery/__init__.py", line 75, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/bdc_collection_builder/celery/tasks.py", line 314, in correction
    raise e
  File "/app/bdc_collection_builder/celery/tasks.py", line 311, in correction
    raise RuntimeError(f'Processor not supported. Check collection {collection.name} metadata processors')
RuntimeError: Processor not supported. Check collection S2_MSI_L2_SR_LASRC metadata processors
```

The atm-correction task seeks for property `collection._metadata['processors']`. It seems like the property has been changed. We should review it.

**Comment by raphaelrpl** [comment]
This error was related due invalid collection metadata. The expected key was `processors` which represents a list of processors, but key `processor` found
